import Config

# Note we include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :gitgud_web, GitGud.Web.Endpoint,
  url: [host: "git.limo"],
  cache_static_manifest: "priv/static/cache_manifest.json"
